### ISSUE TITLE
Fix test workflow (caused by libsodium modification)

### ISSUE THREAD

**Issue by 0Tech** [Finschia/finschia-sdk#801] opened 2022-11-17 06:40 UTC
CI fails due to the latest changes of workflow in rc9/v0.46.0.

_Originally posted by @0Tech in https://github.com/line/lbm-sdk/issues/784#issuecomment-1318141371_

**Comment by 0Tech** [comment] 2022-11-17 06:41
Related: #793

**Comment by ulbqb** [comment] 2022-11-18 07:47
The cause seems to be that libsodium is not installed. I'll fix it.

**Comment by ulbqb** [comment] 2022-11-18 09:15
@0Tech
How about adding test.yml to diff target in test.yml?

**Comment by ulbqb** [comment] 2022-11-18 10:23
I think it's better to add itself to diff target in other each yml file as well.

**Comment by tkxkd0159** [comment] 2023-10-31 08:51
Resolved by https://github.com/Finschia/finschia-sdk/pull/803

**Closed by tkxkd0159** 2023-10-31 08:51 UTC
Labels: help wanted, A: CI
